version: "3"

services:
  server-files:
    image: leo2001/api.server-files:1.1
    restart: always
    environment:
      KEY: ${KEY}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
    ports:
      - 8001:8001
    volumes:
      - ~/Documentos/Projects/api.server-files/static/images:/src/api.server-files/static/images
      - ~/Documentos/Projects/api.server-files/static/pdfs:/src/api.server-files/static/pdfs
    