version: "3"

services:
  server-files:
    build: .
    image: api.server-files
    restart: always
    environment:
      KEY: ${KEY}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
    ports:
      - 8001:8001